### ISSUE TITLE
Kafka source command group cannot include the update command

### ISSUE THREAD

**Issue by daisy-ycguo** [maximilien/kn-source-pkg#14]
I checked the source code and confirmed with Kafka source contributor that all fields under Kafka Spec is not able to be updated. I will get an error: “Immutable fields changed” when I try to update. Refer to [here](https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/apis/sources/v1alpha1/kafka_validation.go#L38)

So I need a way to disable the update command, which means, a way to not include update command in the command group.

**Comment by maximilien** [comment]
Closing this since PR is merged
